name: CustomMods
version: '2.4-SNAPSHOT'
main: com.omochiserver.custommods.CustomMods
api-version: 1.18
load: STARTUP
authors: [ omochi ]
description: you are can use fly command , nickname command and config set command
default-permission: true
commands:
  fly:

    description: Fly command.
    usage: "
      /fly [player]
      引数なしで実行すると、実行したプレイヤーの飛行が有効なら無効、無効なら有効になります。
      引数にはプレイヤー名が入ります。プレイヤー名をつけて実行すると、指定したプレイヤーの飛行が無効なら有効、有効なら無効となります。
      いずれの場合も指定されているプレイヤーはクリエイティブモード、スペクテイターモードの場合は失敗します。"
  nickname:
    description: set nickname.
    usage: "
      /nickname [name]
      nameには文字コードを含めて30文字までの文字列が指定できます。
      文字コードにはalternate color codeを使用します。
      セクションの部分は&に置き換えてください。"
    aliases:
      - nick
  setconfig:
    description: set config.
    usage: "
      用法1 コマンドの実行権限を設定 /setconfig [config1] [permission]
      用法2 機能の設定 /setconfig [config2] [detail] [setting]
      
      [config1]にはコマンドの実行権限を設定したいものを入力してください。fly nicknameなかから記述してください。
      [config2]には機能の設定をしたいものを記述してください。 explosionのなかから記述してください。
      
      [permission]にはコマンドの実行権限を記述してください。
      true : すべてのプレイヤーに使用を許可。
      false : すべてのプレイヤーに使用を許可しない。
      op : op権限を持つプレイヤーに使用を許可。
      notop:op権限を持たないプレイヤーに使用を許可
      
      [detail]と[setting]に記述することのできる要素は[config2]の要素によって変わります。
      [config2]、[detail]、[setting]の順で組み合わせを示していきます。
      
      ブロック破壊を無効にする対象にする火の爆発の有無を記述します。
      true ： 火を伴う爆発を対象とする。
      false : 火を伴わない爆発を対象とする。
      all : すべての爆発を対象とする。
      null : どの爆発も対象としない。
      
      explosion : sensing_fire : true 
                                 false
                                 all
                                 null
      
      ブロック破壊を無効にする対象とする爆発の大きさを記述します。
      1~10の間で選択できます。
      複数指定をする場合は、'-'で間をつないでください。
      
      explosion : sensing_radius : 任意の値"
      
